---
title: 'Assignment 1'
output: html_document
---

```{r}
# Construct a list
Zhuhai <- c("Mostly Sunny", 29, 14)
Wuhan <- c("Mostly Sunny", 30, 19)
Shanghai <- c("Cloudy", 26, 12)
Beijing <- c("Rainy", 19, 10)
weather <- list(Zhuhai, Wuhan, Shanghai, Beijing)
print(weather)
```


```{r}
weather <- data.frame(
  city = c("Zhuhai", "Wuhan", "Shanghai", "Beijing"),
  weather = c("Sunny", "Sunny", "Cloudy", "Rainy"),
  high_Tem = c(20, 21, 16, 19),
  low_Tem = c(14, 19, 12, 15)
)
print(weather)
```


```{r, warning=FALSE, message=FALSE}
# Loading package
library(dplyr)

# Read fuel economy data from the file named 'fuel_economy.csv' and
# assign it to the variable 'fuel_eco'
fuel_eco <- read.csv("fuel_economy.csv")

# Select the variables manufacturer, model, year, and fl
newdata <- fuel_eco %>%
  select(manufacturer, model, year, fl)

# Print the variable names
print(colnames(newdata))

# Select all the variables except cty and hwy
newdata <- fuel_eco %>%
  select(-cty, -hwy)

# Print the variable names
print(colnames(newdata))

# Select the models that are suv classes and contain 4 cylinders (variable: cyl)
newdata <- fuel_eco %>%
  filter(class == "suv" & cyl == 4)


# Print the selected models
print(newdata)


# Calculate the mean displacement (variable: displ) and mean highway miles per gallon (variable: hwy)
newdata <- fuel_eco %>%
  summarize(mean_displ = mean(displ), mean_hwy = mean(hwy))

print(newdata)

# Calculate the mean of displ and hwy for 8 cylinders models by manufacture
newdata <- fuel_eco %>%
  filter(cyl == 8) %>%
  group_by(manufacturer) %>%
  summarize(mean_displ = mean(displ), mean_hwy = mean(hwy))

print(newdata)
```

```{r}
# ggplot2 versions of plots
library(ggplot2)
# create dataset
# write your code here
df <- data.frame(
  value = rnorm(100, mean = 0, sd = 1)
)
# plot histogram
# write your code here
ggplot(df, aes(x = value)) +
  geom_histogram(
    binwidth = 0.1,
    fill = "#69b3a2",
    color = "#e9ecef"
  ) +
  ggtitle("Standard normal distribution")
```

```{r}
# write your code here
df <- read.csv("LifeSavings.csv")

ggplot(
  df,
  aes(
    x = sr,
    y = reorder(country, sr)
  )
) +
  geom_bar(stat = "identity") +
  theme_classic() +
  labs(
    x = "Aggregate personal savings",
    y = ""
  )
```
```{r}
df %>%
  mutate(highlight = ifelse(pop75 < 1 & pop15 > 40, T, F)) %>%
  ggplot(
    aes(
      x = sr,
      y = reorder(country, sr)
    )
  ) +
  geom_bar(stat = "identity", aes(fill = highlight)) +
  guides(fill = "none") + # hide the legend
  scale_fill_manual(values = c("lightgray", "#F1A340")) +
  theme_classic() +
  labs(
    x = "Aggregate personal savings",
    y = ""
  )
```


```{r}
# Define the dataframe named 'plotdata'
# Write your code here
plotdata <- data.frame(
  pet = c("Dog", "Cat", "Psyduck", "Fragrant pig", "Lizard"),
  num = c(1600, 2100, 900, 600, 450)
)
# Write your code here
df <- plotdata %>%
  mutate(proportion = 100 * num / sum(num)) %>%
  arrange(desc(proportion))

df$label <- paste0(
  round(df$proportion), "%"
)

ggplot(
  df,
  aes(
    x = "",
    y = proportion,
    fill = reorder(pet, -proportion)
  )
) +
  geom_bar(
    # width = 1,
    stat = "identity",
    color = "black"
  ) +
  scale_fill_brewer("pet", direction = -1) +
  geom_text(aes(label = label),
    position = position_stack(vjust = 0.5)
  ) +
  coord_polar(theta = "y", start = 0, direction = 1) +
  theme_void()
```

